#!/bin/sh

# run after ./init

# build RBAC tables
./yii migrate --migrationPath=@yii/rbac/migrations

# 初始化 RBAC 数据. ./yii rbac/flush 可清空所有授权信息
./yii rbac/init

# 初始化基础表格 (user, lookup, taxonomy 等)
./yii migrate --migrationPath=@drodata/migrations

# 初始化SPU 功能模块相关表格
./yii migrate --migrationPath=@drodata/migrations/sku

# 初始化附件插件所需的 attachment 表格
./yii migrate --migrationPath=@dro/attachment/migrations

# 自有表格
./yii migrate
